name: "environment test"

# Check out the documentation for more info:
# - https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs
on: [push]

jobs:
  check-migrations:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    outputs:
      has-migrations: ${{ steps.whatchanged.outputs.has-migrations }}
    steps:
      - uses: actions/checkout@v1
      - id: whatchanged
        name: whatchanged
        run: |
          echo "::set-output name=has-migrations::yes"

  output-validation:
    runs-on: ubuntu-20.04
    needs: check-migrations
    if: needs.check-migrations.outputs.has-migrations != 'yes' && needs.check-migrations.outputs.has-migrations != 'no'
    steps:
      - name: Notify about invalid output
        run: |
          echo "The 'check-migrations' job produced invalid output:"
          echo "${{needs.check-migrations.outputs.has-migrations}}"
          exit 1

  run-migrations:
    runs-on: ubuntu-20.04
    needs: check-migrations
    if: needs.check-migrations.outputs.has-migrations == 'yes'
    environment:
      # A manual confirmation is enforced using environment protection rules.
      name: run-migrations
    steps:
      - name: Waiting for migations to have run
        run: |
          echo "Waiting for migrations to complete..."
          echo ${{needs.check-migrations.outputs.has-migrations}}

  ############ Post-migration Deployment Pipeline ############
  deploy-after-migrations:
    runs-on: ubuntu-20.04
    needs: run-migrations
    steps:
      - name: Notify about deployment
        run: |
          echo "The following PRs changed..."

  deploy-after-migrations-aws:
    name: deploy-aws
    runs-on: ubuntu-20.04
    needs: deploy-after-migrations
    environment:
      name: production aws
    steps:
      - name: Deploy to AWS
        run: |
          echo "Deploying..."
  deploy-after-migrations-azure:
    name: deploy-azure
    runs-on: ubuntu-20.04
    needs: deploy-after-migrations
    environment:
      name: production azure
    steps:
      - name: Deploy to Azure
        run: |
          echo "Deploying..."

  ############ Direct Deployment Pipeline ############
  deploy-directly:
    runs-on: ubuntu-20.04
    needs: check-migrations
    if: needs.check-migrations.outputs.has-migrations == 'no'
    steps:
      - name: Notify about deployment
        run: |
          echo "The following PRs changed..."

  deploy-directly-aws:
    name: deploy-aws
    runs-on: ubuntu-20.04
    needs: deploy-directly
    environment:
      name: production aws
    steps:
      - name: Deploy to AWS
        run: |
          echo "Deploying..."
  deploy-directly-azure:
    name: deploy-azure
    runs-on: ubuntu-20.04
    needs: deploy-directly
    environment:
      name: production azure
    steps:
      - name: Deploy to Azure
        run: |
          echo "Deploying..."
