name: "environment test"

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on: [push]

# We'll utilize job outputs to pass information between jobs.
# - https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs
jobs:
  check-migrations:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    outputs:
      has-migrations: ${{ steps.whatchanged.outputs.has-migrations }}
    steps:
      - uses: actions/checkout@v1
      - id: whatchanged
        name: whatchanged
        run: |
          echo "::set-output name=has-migrations::yes"

  # output-check:
  #   runs-on: ubuntu-20.04
  #   needs: check-migrations
  #   steps:
  #     - name: Output
  #       run: |
  #         echo "${{needs.check-migrations.outputs.has-migrations}}"

  run-migrations:
    runs-on: ubuntu-20.04
    needs: check-migrations
    if: github.ref == 'refs/heads/main' && needs.check-migrations.outputs.has-migrations == 'yes'
    environment:
      name: run-migrations
    steps:
      - name: Waiting for migations to have run
        run: |
          echo "Waiting for migrations to complete..."
          echo ${{needs.check-migrations.outputs.has-migrations}}

  ############ Post-migration Deployment Pipeline ############
  deploy-after-migrations:
    runs-on: ubuntu-20.04
    needs: run-migrations
    steps:
      - name: Notify about deployment
        run: |
          echo "The following PRs changed..."

  deploy-after-migrations-aws:
    name: deploy-aws
    runs-on: ubuntu-20.04
    needs: deploy-after-migrations
    environment:
      name: production aws
    steps:
      - name: Deploy to AWS
        run: |
          echo "Deploying..."
  deploy-after-migrations-azure:
    name: deploy-azure
    runs-on: ubuntu-20.04
    needs: deploy-after-migrations
    environment:
      name: production azure
    steps:
      - name: Deploy to Azure
        run: |
          echo "Deploying..."

  ############ Direct Deployment Pipeline ############
  deploy-directly:
    runs-on: ubuntu-20.04
    needs: check-migrations
    if: needs.check-migrations.outputs.has-migrations == 'no'
    steps:
      - name: Notify about deployment
        run: |
          echo "The following PRs changed..."

  deploy-directly-aws:
    name: deploy-aws
    runs-on: ubuntu-20.04
    needs: deploy-directly
    environment:
      name: production aws
    steps:
      - name: Deploy to AWS
        run: |
          echo "Deploying..."
  deploy-directly-azure:
    name: deploy-azure
    runs-on: ubuntu-20.04
    needs: deploy-directly
    environment:
      name: production azure
    steps:
      - name: Deploy to Azure
        run: |
          echo "Deploying..."
