name: "label test"

# Check out the documentation for more info:
# - https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  pull_request:
    types: [synchronize, labeled, unlabeled]

jobs:
  requires-translations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: check-label
        run: |
          # Fix our shell to proper bash so the syntax below will work.
          sudo mv /bin/sh /bin/sh-dash
          sudo ln -s /bin/bash /bin/sh

          echo "Checking if PR has label 'invalid' (if true, will fail)..."
          [[ "${{ contains(github.event.pull_request.labels.*.name, 'invalid') }}" == "true" ]] && exit 1 || exit 0
