name: "label test"

# Check out the documentation for more info:
# - https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    types: [labeled, unlabeled]

jobs:
  fail-if-label:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'invalid')
    steps:
      - uses: actions/checkout@v1

      - name: whatchanged
        run: |
          echo "Testing..."
